### 상품 추가 (셀러)
POST localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스 2"
}

### 상품 아이템 추가 (셀러)
POST localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 100000
}

### 상품 수정 (셀러)
PUT localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 수정 (셀러)
PUT localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

{
  "id": 1,
  "count": 1,
  "name": "260",
  "price": 100000
}

### 상품 삭제
DELETE localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 삭제
DELETE localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM5Nzk0MTIyLCJleHAiOjE3Mzk4ODA1MjJ9.Pyy5Qbc4ILgTFjc3I1qfuqIjdrRHAEoEcMt6mTVQCKs

### 상품 검색
GET localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET localhost:8082/search/product/detail?productId=1
Content-Type: application/json

### 카트 추가
POST localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsRnFXNUVCNGhxMlBGN0NUVXJDTzd2WXEvZDEyM3BKd1M2MjFpZVl0VFdvPSIsImp0aSI6ImdHOU9iYytuNllVeFd0ZC9kQldiMkE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE3Mzk4Mzc1MTgsImV4cCI6MTczOTkyMzkxOH0.YweAzEfDPBojDa0SjYj5a8n8ppF9Q4GDl4DwfHDyryk

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "id": 1,
      "name": "270",
      "count": 1,
      "price": 100000
    }
  ],
  "sellerId": 1,
  "name": "나이키 에어포스 2"
}